### ISSUE TITLE
🐛 Bug Report: Duplicate knex packages after installing Bazaar plugin

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/backstage#14452]
### 📜 Description

Bazaar Plugin giving below error on building Backstage Docker file after installation of Bazaar Plugin

```

#17 [build 5/8] COPY --chown=node:node . .
#17 DONE 130.6s

#18 [build 6/8] RUN yarn tsc
#18 0.743 yarn run v1.22.19
#18 0.792 warning Skipping preferred cache folder "/home/node/.cache/yarn" because it is not writable.
#18 0.792 warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
#18 0.814 $ tsc
#18 21.26 packages/backend/src/plugins/bazaar.ts:11:5 - error TS2322: Type 'import("/app/node_modules/@backstage/backend-common/dist/index").PluginDatabaseManager' is not assignable to type 'import("/app/node_modules/@backstage/plugin-bazaar-backend/node_modules/@backstage/backend-common/dist/index").PluginDatabaseManager'.
#18 21.26   The types returned by 'getClient()' are incompatible between these types.
#18 21.26     Type 'Promise<import("/app/node_modules/knex/types/index").Knex<any, any[]>>' is not assignable to type 'Promise<import("/app/node_modules/@backstage/backend-plugin-api/node_modules/knex/types/index").Knex<any, any[]>>'.
#18 21.26       Type 'import("/app/node_modules/knex/types/index").Knex<any, any[]>' is not assignable to type 'import("/app/node_modules/@backstage/backend-plugin-api/node_modules/knex/types/index").Knex<any, any[]>'.
#18 21.26         Types of property 'raw' are incompatible.
#18 21.26           Type 'import("/app/node_modules/knex/types/index").Knex.RawBuilder<any, any>' is not assignable to type 'import("/app/node_modules/@backstage/backend-plugin-api/node_modules/knex/types/index").Knex.RawBuilder<any, any>'.
#18 21.26             Types of parameters 'value' and 'value' are incompatible.
#18 21.26               Type 'import("/app/node_modules/@backstage/backend-plugin-api/node_modules/knex/types/index").Knex.Value' is not assignable to type 'import("/app/node_modules/knex/types/index").Knex.Value'.
#18 21.26                 Type 'object' is not assignable to type 'Value'.
#18 21.26 
#18 21.26 11     database: env.database,
#18 21.26        ~~~~~~~~
#18 21.26 
#18 21.26   node_modules/@backstage/plugin-bazaar-backend/dist/index.d.ts:10:5
#18 21.26     10     database: PluginDatabaseManager;
#18 21.26            ~~~~~~~~
#18 21.26     The expected type comes from property 'database' which is declared here on type 'RouterOptions'
#18 21.26 
#18 21.26 packages/backend/src/plugins/bazaar.ts:12:19 - error TS2339: Property 'identity' does not exist on type 'PluginEnvironment'.
#18 21.26 
#18 21.26 12     identity: env.identity,
#18 21.26                      ~~~~~~~~
#18 21.26 
#18 21.26 
#18 21.26 Found 2 errors in the same file, starting at: packages/backend/src/plugins/bazaar.ts:11
#18 21.26 
#18 21.37 error Command failed with exit code 2.
#18 21.37 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#18 ERROR: executor failed running [/bin/sh -c yarn tsc]: exit code: 2
------
 > [build 6/8] RUN yarn tsc:
#18 21.26 packages/backend/src/plugins/bazaar.ts:12:19 - error TS2339: Property 'identity' does not exist on type 'PluginEnvironment'.
#18 21.26 
#18 21.26 12     identity: env.identity,
#18 21.26                      ~~~~~~~~
#18 21.26 
#18 21.26 
#18 21.26 Found 2 errors in the same file, starting at: packages/backend/src/plugins/bazaar.ts:11
#18 21.26 
#18 21.37 error Command failed with exit code 2.
#18 21.37 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
ERROR: failed to solve: executor failed running [/bin/sh -c yarn tsc]: exit code: 2
Error: buildx failed with: ERROR: failed to solve: executor failed running [/bin/sh -c yarn tsc]: exit code: 2

```

### 👍 Expected behavior

It should not give above error and Dockerfile should build successfully.

### 👎 Actual Behavior with Screenshots

On Dockerfile building , `yarn tsc ` giving below error
```

#17 [build 5/8] COPY --chown=node:node . .
#17 DONE 130.6s

#18 [build 6/8] RUN yarn tsc
#18 0.743 yarn run v1.22.19
#18 0.792 warning Skipping preferred cache folder "/home/node/.cache/yarn" because it is not writable.
#18 0.792 warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000".
#18 0.814 $ tsc
#18 21.26 packages/backend/src/plugins/bazaar.ts:11:5 - error TS2322: Type 'import("/app/node_modules/@backstage/backend-common/dist/index").PluginDatabaseManager' is not assignable to type 'import("/app/node_modules/@backstage/plugin-bazaar-backend/node_modules/@backstage/backend-common/dist/index").PluginDatabaseManager'.
#18 21.26   The types returned by 'getClient()' are incompatible between these types.
#18 21.26     Type 'Promise<import("/app/node_modules/knex/types/index").Knex<any, any[]>>' is not assignable to type 'Promise<import("/app/node_modules/@backstage/backend-plugin-api/node_modules/knex/types/index").Knex<any, any[]>>'.
#18 21.26       Type 'import("/app/node_modules/knex/types/index").Knex<any, any[]>' is not assignable to type 'import("/app/node_modules/@backstage/backend-plugin-api/node_modules/knex/types/index").Knex<any, any[]>'.
#18 21.26         Types of property 'raw' are incompatible.
#18 21.26           Type 'import("/app/node_modules/knex/types/index").Knex.RawBuilder<any, any>' is not assignable to type 'import("/app/node_modules/@backstage/backend-plugin-api/node_modules/knex/types/index").Knex.RawBuilder<any, any>'.
#18 21.26             Types of parameters 'value' and 'value' are incompatible.
#18 21.26               Type 'import("/app/node_modules/@backstage/backend-plugin-api/node_modules/knex/types/index").Knex.Value' is not assignable to type 'import("/app/node_modules/knex/types/index").Knex.Value'.
#18 21.26                 Type 'object' is not assignable to type 'Value'.
#18 21.26 
#18 21.26 11     database: env.database,
#18 21.26        ~~~~~~~~
#18 21.26 
#18 21.26   node_modules/@backstage/plugin-bazaar-backend/dist/index.d.ts:10:5
#18 21.26     10     database: PluginDatabaseManager;
#18 21.26            ~~~~~~~~
#18 21.26     The expected type comes from property 'database' which is declared here on type 'RouterOptions'
#18 21.26 
#18 21.26 packages/backend/src/plugins/bazaar.ts:12:19 - error TS2339: Property 'identity' does not exist on type 'PluginEnvironment'.
#18 21.26 
#18 21.26 12     identity: env.identity,
#18 21.26                      ~~~~~~~~
#18 21.26 
#18 21.26 
#18 21.26 Found 2 errors in the same file, starting at: packages/backend/src/plugins/bazaar.ts:11
#18 21.26 
#18 21.37 error Command failed with exit code 2.
#18 21.37 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#18 ERROR: executor failed running [/bin/sh -c yarn tsc]: exit code: 2
------
 > [build 6/8] RUN yarn tsc:
#18 21.26 packages/backend/src/plugins/bazaar.ts:12:19 - error TS2339: Property 'identity' does not exist on type 'PluginEnvironment'.
#18 21.26 
#18 21.26 12     identity: env.identity,
#18 21.26                      ~~~~~~~~
#18 21.26 
#18 21.26 
#18 21.26 Found 2 errors in the same file, starting at: packages/backend/src/plugins/bazaar.ts:11
#18 21.26 
#18 21.37 error Command failed with exit code 2.
#18 21.37 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
ERROR: failed to solve: executor failed running [/bin/sh -c yarn tsc]: exit code: 2
Error: buildx failed with: ERROR: failed to solve: executor failed running [/bin/sh -c yarn tsc]: exit code: 2

```

### 👟 Reproduction steps

Follow below links to install `Bazaar Backend` and `Bazaar Fronted` Plugin 

[Bazaar Backend](https://github.com/backstage/backstage/tree/master/plugins/bazaar-backend)
[Bazaar Fronted](https://github.com/backstage/backstage/tree/master/plugins/bazaar)

### 🖥️ Your Environment

output of `yarn backstage-cli info` is 

---

```
[backstage@backstage backstage-conf-repo-original]$ yarn backstage-cli info
yarn run v1.22.19
$ /home/backstage/backstage-conf-repo/backstage-conf-repo-original/node_modules/.bin/backstage-cli info
OS:   Linux 3.10.0-1160.71.1.el7.x86_64 - linux/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.3
  @backstage/backend-common                        0.14.0, 0.14.1, 0.15.1
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.2, 0.3.3
  @backstage/catalog-client                        1.0.3, 1.0.4, 1.1.0
  @backstage/catalog-model                         1.0.3, 1.1.0, 1.1.1
  @backstage/cli-common                            0.1.10, 0.1.9
  @backstage/cli                                   0.17.2
  @backstage/config-loader                         1.1.2, 1.1.3, 1.1.4
  @backstage/config                                1.0.1, 1.0.2, 1.0.3
  @backstage/core-app-api                          1.0.3
  @backstage/core-components                       0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.9.5
  @backstage/core-plugin-api                       1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7
  @backstage/errors                                1.1.0, 1.0.0, 1.1.1, 1.1.2
  @backstage/integration-react                     1.1.2, 1.1.1
  @backstage/integration                           1.2.1, 1.2.2, 1.3.0, 1.3.1
  @backstage/plugin-api-docs                       0.8.6
  @backstage/plugin-app-backend                    0.3.33
  @backstage/plugin-auth-backend                   0.14.1
  @backstage/plugin-auth-node                      0.2.2, 0.2.3
  @backstage/plugin-catalog-backend-module-github  0.1.5
  @backstage/plugin-catalog-backend                1.2.0, 1.3.0
  @backstage/plugin-catalog-common                 1.0.3, 1.0.4, 1.0.5, 1.0.6
  @backstage/plugin-catalog-graph                  0.2.18
  @backstage/plugin-catalog-import                 0.8.9
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.1, 1.1.3, 1.1.4
  @backstage/plugin-catalog                        1.3.0
  @backstage/plugin-github-actions                 0.5.6
  @backstage/plugin-home                           0.4.22
  @backstage/plugin-org                            0.5.6
  @backstage/plugin-permission-common              0.6.2, 0.6.3, 0.6.4
  @backstage/plugin-permission-node                0.6.2, 0.6.3
  @backstage/plugin-permission-react               0.4.2, 0.4.4, 0.4.5
  @backstage/plugin-proxy-backend                  0.2.27
  @backstage/plugin-scaffolder-backend             1.3.0
  @backstage/plugin-scaffolder-common              1.1.1, 1.1.2
  @backstage/plugin-scaffolder                     1.3.0
  @backstage/plugin-search-backend-module-pg       0.3.4
  @backstage/plugin-search-backend-node            0.6.2
  @backstage/plugin-search-backend                 0.5.3
  @backstage/plugin-search-common                  0.3.5, 1.0.0, 1.0.1
  @backstage/plugin-search-react                   0.2.1
  @backstage/plugin-search                         0.9.0
  @backstage/plugin-shortcuts                      0.3.2
  @backstage/plugin-stack-overflow                 0.1.2
  @backstage/plugin-tech-radar                     0.5.13
  @backstage/plugin-techdocs-backend               1.1.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.1
  @backstage/plugin-techdocs-node                  1.1.2
  @backstage/plugin-techdocs-react                 1.0.1
  @backstage/plugin-techdocs                       1.2.0
  @backstage/plugin-todo-backend                   0.1.32
  @backstage/plugin-todo                           0.2.11
  @backstage/plugin-user-settings                  0.4.5
  @backstage/release-manifests                     0.0.4
  @backstage/test-utils                            1.1.1
  @backstage/theme                                 0.2.15, 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.58s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Looks like you have quite a couple of duplicated packages. Does running this fix the issue?

```bash
yarn backstage-cli versions:check --fix
```

**Comment by prasoon-pxc** [comment]
Hi @Rugvip , I have tried running above cmd, here is the output,
---
```
[backstage@backstage backstage-conf-repo-original]$ yarn backstage-cli versions:check --fix
yarn run v1.22.19
$ /home/backstage/backstage-conf-repo/backstage-conf-repo-original/node_modules/.bin/backstage-cli versions:check --fix
The following packages can be deduplicated by updating dependencies in package.json

  @backstage/backend-common @ ^0.14.0 should be changed to ^0.15.2
  @backstage/backend-common @ ^0.14.1 should be changed to ^0.15.2
  @backstage/cli @ ^0.17.2 should be changed to ^0.20.0
  @backstage/core-components @ ^0.10.0 should be changed to ^0.11.2
  @backstage/core-components @ ^0.9.0 should be changed to ^0.11.2
  @backstage/core-components @ ^0.9.5 should be changed to ^0.11.2
  @backstage/errors @ 1.1.0 should be changed to ^1.1.2
  @backstage/plugin-permission-common @ ^0.6.2 should be changed to ^0.7.0
  @backstage/plugin-permission-common @ ^0.6.3 should be changed to ^0.7.0
  @backstage/plugin-permission-common @ ^0.6.4 should be changed to ^0.7.0
  @backstage/plugin-permission-node @ ^0.6.2 should be changed to ^0.7.0
  @backstage/plugin-permission-node @ ^0.6.3 should be changed to ^0.7.0
  @backstage/plugin-search-common @ ^0.3.5 should be changed to ^1.1.0
  @backstage/plugin-search-react @ ^0.2.1 should be changed to ^1.2.0
  @backstage/release-manifests @ ^0.0.4 should be changed to ^0.0.6

Done in 0.92s.
```
---
- Then, running `yarn tsc` giving same error,

```
[backstage@backstage backstage-conf-repo-original]$ yarn tsc
yarn run v1.22.19
$ tsc
packages/backend/src/plugins/bazaar.ts:12:19 - error TS2339: Property 'identity' does not exist on type 'PluginEnvironment'.

12     identity: env.identity,
                     ~~~~~~~~


Found 1 error in packages/backend/src/plugins/bazaar.ts:12

error Command failed with exit code 2.
```

**Comment by prasoon-pxc** [comment]
I also tried updating the backstage version from `1.3.0` to `1.7.1` and then check the output of `yarn backstage-cli info` 

---
```
[backstage@backstage backstage-conf-repo-original]$ yarn backstage-cli info
yarn run v1.22.19
$ /home/backstage/backstage-conf-repo/backstage-conf-repo-original/node_modules/.bin/backstage-cli info
OS:   Linux 3.10.0-1160.71.1.el7.x86_64 - linux/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.1

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-app-api                       0.2.2
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/backend-test-utils                    0.1.29
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2
  @backstage/core-plugin-api                       1.0.7
  @backstage/errors                                1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-bazaar-backend                 0.2.0
  @backstage/plugin-catalog-backend-module-github  0.1.8
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-home                           0.4.26
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.0
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-shortcuts                      0.3.2
  @backstage/plugin-stack-overflow                 0.1.6
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-todo-backend                   0.1.34
  @backstage/plugin-todo                           0.2.12
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 0.51s
```

--- 
- And then again trying to install bazaar backend plugin and  run `yarn tsc` but getting the same error as below:

```
[backstage@backstage backstage-conf-repo-original]$ yarn tsc
yarn run v1.22.19
$ tsc
packages/backend/src/plugins/bazaar.ts:12:19 - error TS2339: Property 'identity' does not exist on type 'PluginEnvironment'.

12     identity: env.identity,
                     ~~~~~~~~


Found 1 error in packages/backend/src/plugins/bazaar.ts:12

```

**Comment by prasoon-pxc** [comment]
I resolved this issue by doing following steps:
---

- Installed lower version of bazaar plugins

`yarn add --cwd packages/backend @backstage/plugin-bazaar-backend@0.1.18`
`yarn add --cwd packages/app @backstage/plugin-bazaar@0.1.24`

- Then after installing , I removed the `identity: env.identity,` this line from `bazaar.ts` file
  - My `bazaar.ts` file now looking like below:
 ```
import { PluginEnvironment } from '../types';
import { createRouter } from '@backstage/plugin-bazaar-backend';
import { Router } from 'express';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
  });
}
```

I do not know what is the use of `IdentityApi` here but this solved my problems, but I would like to know more about the exact issue in latest plugin

**Comment by anicke** [comment]
You have to update the "PluginEnvironment" to include the "identity" property. This will probably not work with Backstage 1.3.0 but if you update to 1.7.0 and then do the following:

Update your PluginEnvironment typing. Update your backstage instance accordingly:
https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/src/types.ts#L24

Then update the "makeCreateEnv" function to add the additional env properties (like identity).
https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/src/index.ts#L44

**Comment by prasoon-pxc** [comment]
@anicke --> I will try this .

**Comment by prasoon-pxc** [comment]
Thanks @anicke It resolves the issue
