### ISSUE TITLE
🐛 Bug Report: MicrosoftGraphOrgEntityProvider | Error after updating to version 1.25.0

### ISSUE THREAD

**Issue by padupe** [backstage/backstage#23922]
### 📜 Description

After updating to the aforementioned version, we are receiving the following error message:

```
[1] 01/04/2024 16:56:24 [Backstage] | [error]: MicrosoftGraphOrgEntityProvider:default refresh failed, TypeError: coreUtil.randomUUID is not a function coreUtil.randomUUID is not a function
[0] WARNING in ../../node_modules/@azure/identity/dist-esm/src/msal/utils.browser.js 127:15-25
[0] export 'randomUUID' (imported as 'randomUUID') was not found in '@azure/core-util' (possible exports: computeSha256Hash, computeSha256Hmac, delay, getErrorMessage, getRandomIntegerInclusive, isError, isNode, isObject)
[0] 
[0] webpack compiled with 1 warning
```

### 👍 Expected behavior

No integration errors.

### 👎 Actual Behavior with Screenshots

It is not possible to carry out the authentication process, as we use integration with Microsoft for this purpose.

### 👟 Reproduction steps

1. Run
```
yarn backstage-cli versions:bump
```

2. Run
```
yarn dev
```

### 🖥️ Your Environment

```
OS:   Linux 6.5.0-26-generic - linux/x64
node: v18.16.1
yarn: 1.22.19
cli:  0.26.2 (installed)
backstage:  1.25.0

Dependencies:
  @backstage/app-defaults                                          1.5.3
  @backstage/backend-app-api                                       0.6.2
  @backstage/backend-common                                        0.21.6
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.9
  @backstage/backend-plugin-api                                    0.6.16
  @backstage/backend-tasks                                         0.5.21
  @backstage/catalog-client                                        1.6.3
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.2
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.3
  @backstage/core-compat-api                                       0.2.3
  @backstage/core-components                                       0.10.0, 0.11.2, 0.12.5, 0.14.3
  @backstage/core-plugin-api                                       1.9.1
  @backstage/dev-utils                                             1.0.30
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.3
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-analytics-module-ga4                           0.2.3
  @backstage/plugin-api-docs                                       0.11.3
  @backstage/plugin-app-backend                                    0.3.64
  @backstage/plugin-app-node                                       0.1.16
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.8
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.8
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.11
  @backstage/plugin-auth-backend-module-github-provider            0.1.13
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.13
  @backstage/plugin-auth-backend-module-google-provider            0.1.13
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.11
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.13
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.9
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.7
  @backstage/plugin-auth-backend-module-okta-provider              0.0.9
  @backstage/plugin-auth-backend                                   0.22.3
  @backstage/plugin-auth-node                                      0.4.11
  @backstage/plugin-auth-react                                     0.0.3
  @backstage/plugin-catalog-backend-module-github                  0.5.7
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.24
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.14
  @backstage/plugin-catalog-backend                                1.21.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.3
  @backstage/plugin-catalog-import                                 0.10.9
  @backstage/plugin-catalog-node                                   1.11.0
  @backstage/plugin-catalog-react                                  1.11.2
  @backstage/plugin-catalog                                        1.18.2
  @backstage/plugin-dynatrace                                      10.0.2
  @backstage/plugin-events-node                                    0.3.2
  @backstage/plugin-home-react                                     0.1.11
  @backstage/plugin-home                                           0.7.2
  @backstage/plugin-kubernetes-backend                             0.16.3
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.10
  @backstage/plugin-kubernetes-react                               0.3.3
  @backstage/plugin-kubernetes                                     0.11.8
  @backstage/plugin-org                                            0.6.23
  @backstage/plugin-permission-backend                             0.5.40
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.27
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-proxy-backend                                  0.4.14
  @backstage/plugin-scaffolder-backend-module-azure                0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.8
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.6
  @backstage/plugin-scaffolder-backend-module-github               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.2
  @backstage/plugin-scaffolder-backend                             1.22.3
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.2
  @backstage/plugin-scaffolder-react                               1.8.3
  @backstage/plugin-scaffolder                                     1.19.2
  @backstage/plugin-search-backend-module-catalog                  0.1.21
  @backstage/plugin-search-backend-module-pg                       0.5.25
  @backstage/plugin-search-backend-module-techdocs                 0.1.21
  @backstage/plugin-search-backend-node                            1.2.20
  @backstage/plugin-search-backend                                 1.5.6
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.9
  @backstage/plugin-search                                         1.4.9
  @backstage/plugin-signals-node                                   0.1.2
  @backstage/plugin-signals-react                                  0.0.2
  @backstage/plugin-sonarqube-backend                              0.2.18
  @backstage/plugin-sonarqube-react                                0.1.14
  @backstage/plugin-sonarqube                                      0.7.15
  @backstage/plugin-tech-radar                                     0.7.2
  @backstage/plugin-techdocs-backend                               1.10.3
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.8
  @backstage/plugin-techdocs-node                                  1.12.2
  @backstage/plugin-techdocs-react                                 1.2.2
  @backstage/plugin-techdocs                                       1.10.3
  @backstage/plugin-user-settings                                  0.8.4
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.3
  @backstage/theme                                                 0.2.18, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
Done in 0.65s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by padupe** [comment]
PSC @claudinei-ferreira @rayleshh

**Comment by freben** [comment]
@padupe you need to upgrade your project to typescript 5. See the release notes for the versions that you upgraded through.

**Comment by padupe** [comment]
@freben Do you have the reference for this documentation?

**Comment by awanlin** [comment]
TS was upgraded to v5 in the `1.13` release: https://github.com/backstage/backstage/blob/master/docs/releases/v1.13.0-next.2-changelog.md#patch-changes-15

**Comment by padupe** [comment]
> TS was upgraded to v5 in the `1.13` release: https://github.com/backstage/backstage/blob/master/docs/releases/v1.13.0-next.2-changelog.md#patch-changes-15

I updated the TS version, and I keep getting the error

**Comment by freben** [comment]
Did you

- upgrade in the *root* `package.json`,
- followed by running `yarn install`,
- and then `yarn tsc:full`?

**Comment by padupe** [comment]
After run `yarn tsc:full`:

```
Found 343 errors in 43 files.

Errors  Files
     3  node_modules/@backstage/core-app-api/dist/index.d.ts:25
    81  node_modules/@backstage/core-components/dist/index.d.ts:63
     2  node_modules/@backstage/core-plugin-api/dist/index.d.ts:49
     3  node_modules/@backstage/frontend-plugin-api/dist/index.d.ts:2
     1  node_modules/@backstage/integration-react/dist/index.d.ts:243
    22  node_modules/@backstage/plugin-api-docs/dist/index.d.ts:24
     3  node_modules/@backstage/plugin-catalog-graph/dist/index.d.ts:151
    11  node_modules/@backstage/plugin-catalog-import/dist/index.d.ts:28
    25  node_modules/@backstage/plugin-catalog-react/dist/index.d.ts:200
    13  node_modules/@backstage/plugin-catalog/dist/index.d.ts:176
     1  node_modules/@backstage/plugin-dynatrace/dist/index.d.ts:21
     2  node_modules/@backstage/plugin-home-react/dist/index.d.ts:11
    18  node_modules/@backstage/plugin-home/dist/index.d.ts:211
    23  node_modules/@backstage/plugin-kubernetes-react/dist/index.d.ts:376
     1  node_modules/@backstage/plugin-kubernetes/dist/index.d.ts:26
     9  node_modules/@backstage/plugin-org/dist/index.d.ts:18
     1  node_modules/@backstage/plugin-permission-react/dist/index.d.ts:25
     2  node_modules/@backstage/plugin-scaffolder-backend-module-github/node_modules/@octokit/app/dist-types/index.d.ts:16
     2  node_modules/@backstage/plugin-scaffolder-backend-module-github/node_modules/octokit/dist-types/app.d.ts:46
     1  node_modules/@backstage/plugin-scaffolder-react/dist/index.d.ts:356
     3  node_modules/@backstage/plugin-scaffolder/dist/index.d.ts:197
    26  node_modules/@backstage/plugin-search-react/dist/index.d.ts:72
    10  node_modules/@backstage/plugin-search/dist/index.d.ts:54
     3  node_modules/@backstage/plugin-sonarqube/dist/index.d.ts:35
     2  node_modules/@backstage/plugin-tech-radar/dist/index.d.ts:45
     2  node_modules/@backstage/plugin-techdocs-react/dist/index.d.ts:188
    24  node_modules/@backstage/plugin-techdocs/dist/index.d.ts:203
    18  node_modules/@backstage/plugin-user-settings/dist/index.d.ts:50
     1  node_modules/@backstage/test-utils/dist/index.d.ts:486
    11  node_modules/@drodil/backstage-plugin-qeta/dist/index.d.ts:18
     1  node_modules/@mui/base/useMenu/MenuProvider.d.ts:15
     1  node_modules/@mui/base/useSelect/SelectProvider.d.ts:15
     1  node_modules/@mui/base/useTabs/TabsProvider.d.ts:18
     1  node_modules/@mui/base/useTabsList/TabsListProvider.d.ts:15
     1  node_modules/@mui/base/utils/ClassNameConfigurator.d.ts:23
     1  node_modules/@mui/system/GlobalStyles/GlobalStyles.d.ts:9
     1  node_modules/@mui/system/cssVars/getInitColorSchemeScript.d.ts:42
     1  node_modules/@types/node/globals.d.ts:72
     2  node_modules/@types/ws/index.d.ts:321
     6  node_modules/io-ts/lib/index.d.ts:1387
     1  node_modules/react-markdown/lib/ast-to-react.d.ts:17
     1  packages/app/src/components/signInPage/customProvider.tsx:9
     1  packages/backend/src/plugins/kubernetes.ts:10
 ```

**Comment by padupe** [comment]
> Você fez
> 
> * atualizar na _raiz_ `package.json` ,
> * seguido de corrida `yarn install`,
> * e então `yarn tsc:full`?
> 
> O erro que você colou aponta para um recurso que foi introduzido no ts5, portanto, tenho certeza de que esse é o problema específico `const`. Observe que isso não está relacionado ao `randomUUID`problema.

"export 'randomUUID' (imported as 'randomUUID') was not found in '@azure/core-util'"
I believe "ramdomUUID" is not exists. :/

**Comment by benjdlambert** [comment]
What are some of the errors that you're seeing now with `tsc:full` after upgrading to 1.25.0?

**Comment by padupe** [comment]
> What are some of the errors that you're seeing now with `tsc:full` after upgrading to 1.25.0?

Some examples of errors when running `tsc:full`:

```
node_modules/@backstage/plugin-catalog/dist/index.d.ts:176:73 - error TS2694: Namespace 'React' has no exported member 'JSX'.

176 declare function AboutContent(props: AboutContentProps): React__default.JSX.Element;
                                                                            ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:190:69 - error TS2694: Namespace 'React' has no exported member 'JSX'.

190 declare function AboutField(props: AboutFieldProps): React__default.JSX.Element;
                                                                        ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:213:83 - error TS2694: Namespace 'React' has no exported member 'JSX'.

213 declare function CatalogKindHeader(props: CatalogKindHeaderProps): React__default.JSX.Element;
                                                                                      ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:248:48 - error TS2694: Namespace 'React' has no exported member 'JSX'.

248     (props: CatalogTableProps): React__default.JSX.Element;
                                                   ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:318:48 - error TS2694: Namespace 'React' has no exported member 'JSX'.

318     (props: EntityLayoutProps): React__default.JSX.Element;
                                                   ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:335:56 - error TS2694: Namespace 'React' has no exported member 'JSX'.

335 declare function EntityOrphanWarning(): React__default.JSX.Element;
                                                           ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:352:58 - error TS2694: Namespace 'React' has no exported member 'JSX'.

352 declare function EntityRelationWarning(): React__default.JSX.Element | null;
                                                             ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:367:64 - error TS2694: Namespace 'React' has no exported member 'JSX'.

367 declare function EntityProcessingErrorsPanel(): React__default.JSX.Element | null;
                                                                   ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:386:48 - error TS2694: Namespace 'React' has no exported member 'JSX'.

386     (props: EntitySwitchProps): React__default.JSX.Element;
                                                   ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:438:15 - error TS2694: Namespace 'React' has no exported member 'JSX'.

438 }) => React$1.JSX.Element;
                  ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:445:15 - error TS2694: Namespace 'React' has no exported member 'JSX'.

445 }) => React$1.JSX.Element;
                  ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:617:73 - error TS2694: Namespace 'React' has no exported member 'JSX'.

617 declare const EntityLinksCard: (props: EntityLinksCardProps) => React$1.JSX.Element;
                                                                            ~~~

node_modules/@backstage/plugin-catalog/dist/index.d.ts:619:75 - error TS2694: Namespace 'React' has no exported member 'JSX'.

619 declare const EntityLabelsCard: (props: EntityLabelsCardProps) => React$1.JSX.Element;
                                                                              ~~~

node_modules/@backstage/plugin-dynatrace/dist/index.d.ts:21:41 - error TS2694: Namespace 'React' has no exported member 'JSX'.

21 declare const DynatraceTab: () => react.JSX.Element;
                                           ~~~

node_modules/@backstage/plugin-home-react/dist/index.d.ts:11:13 - error TS2694: Namespace 'React' has no exported member 'JSX'.

11 }) => React.JSX.Element;
               ~~~

node_modules/@backstage/plugin-home-react/dist/index.d.ts:81:82 - error TS2694: Namespace 'React' has no exported member 'JSX'.

81 }): _backstage_core_plugin_api.Extension<(props: CardExtensionProps<T>) => React.JSX.Element>;
                                                                                    ~~~

node_modules/@backstage/plugin-home/dist/index.d.ts:211:33 - error TS2694: Namespace 'React' has no exported member 'JSX'.

211     emptyState?: React__default.JSX.Element;
                                    ~~~

node_modules/@backstage/plugin-home/dist/index.d.ts:238:13 - error TS2694: Namespace 'React' has no exported member 'JSX'.

238 }) => React.JSX.Element;
                ~~~

node_modules/@backstage/plugin-home/dist/index.d.ts:248:13 - error TS2694: Namespace 'React' has no exported member 'JSX'.
```

**Comment by padupe** [comment]
> I think that this is pointing to `@types/react` and/or `@types/react-dom` being out of date. Do you have something similar to this in your root `package.json`? https://github.com/backstage/backstage/blob/master/package.json#L89-L90

Resolved.
However, the error initially indicated persists:

```
[0] WARNING in ../../node_modules/@azure/identity/dist-esm/src/msal/utils.browser.js 127:15-25
[0] export 'randomUUID' (imported as 'randomUUID') was not found in '@azure/core-util' (possible exports: computeSha256Hash, computeSha256Hmac, delay, getErrorMessage, getRandomIntegerInclusive, isError, isNode, isObject)
[0] 
[0] webpack compiled with 1 warning
```

**Comment by benjdlambert** [comment]
can you try removing `@azure/identity` and `@azure/core-util` from your `yarn.lock` and do a `yarn install`? It looks like some of those packages are incompatible with each other, but not sure of the fix for this.

**Comment by padupe** [comment]
> can you try removing `@azure/identity` and `@azure/core-util` from your `yarn.lock` and do a `yarn install`? It looks like some of those packages are incompatible with each other, but not sure of the fix for this.

That solved it!
Now it's time to adapt the code (it was in version 1.20.3) to the new one.
