### ISSUE TITLE
 npx @backstage/create-app errors with TypeError: fs__default.default.rm is not a function

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [backstage/backstage#14327]
## Expected Behavior

following the instructions here: https://backstage.io/docs/getting-started/#create-your-backstage-app I expect to be able to create an app.

## Actual Behavior

I receive an error.
```
matthewboyle in ~/Dev/backstage-explore λ npx @backstage/create-app

npx: installed 71 in 3.146s
? Enter a name for the app [required] matt

Creating the app...

TypeError: fs__default.default.rm is not a function

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

```
## Steps to Reproduce

Running npx @backstage/create-app using node 14.0.0.

## Context

I fixed it by upgrading to v16.0.0. when I upgraded to v16.0.0, I received a different error:
`Error: Failed to read git config, Error: EEXIST: file already exists, mkdir '/var/folders/6c/565l_36j5f93vczwq09z9_100000gn/T/git-temp-dir'`.
I fixed _this_ by running rm -rf /var/folders/6c/565l_36j5f93vczwq09z9_100000gn/T/git-temp-dir. Once done,  npx @backstage/create-app worked for me.

I'm mainly raising this issue so if others see it and google it, they find the solution. Might be good to update the docs to outline what the minimum supported node version is today as I don't see it.

Thanks!

**Comment by Rugvip** [comment]
Closing this since we no longer support Node.js 14. The tmp dir issue is being fixed in #15459
