### ISSUE TITLE
🐛 Bug Report: TypeError: meter.createGauge is not a function

### ISSUE THREAD

**Issue by darrenyung** [backstage/backstage#29430]
### 📜 Description

When upgrading to 1.37.0, at runtime, we are getting an error on start-up for our backend in our deployed env. `yarn dev` starts fine.

### 👍 Expected behavior

Application starts fine

### 👎 Actual Behavior with Screenshots

Application fails to start.

### 👟 Reproduction steps

1. Upgrade to 1.37.0 according to the release steps.
2. Build docker image and mount image.
3. Observe error at startup.

### 📃 Provide the context for the Bug.

[2m2025-04-01T02:25:47.536Z[22m [34mbackstage[39m [31merror[39m Plugin 'search' threw an error during startup, waiting for 3 other plugins to finish before shutting down the process. Failed to instantiate service 'core.scheduler' for 'search' because the factory function threw an error, TypeError: meter.createGauge is not a function [36mtype[39m="initialization" [36mstack[39m="Error: Failed to instantiate service 'core.scheduler' for 'search' because the factory function threw an error, TypeError: meter.createGauge is not a function\n at [/app/node_modules/@backstage/backend-app-api/dist/wiring/ServiceRegistry.cjs.js:232:21\n](mailto:/app/node_modules/@backstage/backend-app-api/dist/wiring/ServiceRegistry.cjs.js:232:21%5Cn) at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"

### 🖥️ Your Environment

OS:   Darwin 24.3.0 - darwin/arm64
node: v22.13.0
yarn: 4.6.0
cli:  0.31.0 (installed)
backstage:  1.37.0

Dependencies:
  @backstage/app-defaults                                          1.6.0
  @backstage/backend-app-api                                       1.2.1
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.7.0, 0.8.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.2.0, 0.4.1, 0.5.1
  @backstage/backend-plugin-api                                    0.8.1, 1.2.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    1.3.1
  @backstage/catalog-client                                        1.9.1
  @backstage/catalog-model                                         1.7.3
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.13
  @backstage/cli                                                   0.31.0
  @backstage/config-loader                                         1.10.0
  @backstage/config                                                1.3.2
  @backstage/core-app-api                                          1.16.0
  @backstage/core-compat-api                                       0.3.6, 0.4.0
  @backstage/core-components                                       0.11.2, 0.14.10, 0.15.1, 0.16.4, 0.17.0
  @backstage/core-plugin-api                                       1.10.5
  @backstage/dev-utils                                             1.1.8
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.7
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.11.0
  @backstage/frontend-defaults                                     0.2.0
  @backstage/frontend-plugin-api                                   0.10.0, 0.9.5
  @backstage/frontend-test-utils                                   0.3.0
  @backstage/integration-aws-node                                  0.1.15
  @backstage/integration-react                                     1.2.5
  @backstage/integration                                           1.16.2
  @backstage/plugin-api-docs                                       0.12.5
  @backstage/plugin-app-backend                                    0.5.0
  @backstage/plugin-app-node                                       0.1.31
  @backstage/plugin-app                                            0.1.7
  @backstage/plugin-auth-backend-module-atlassian-provider         0.4.1
  @backstage/plugin-auth-backend-module-auth0-provider             0.2.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.4.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.6
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.3.1
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.2.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.4.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.4.1
  @backstage/plugin-auth-backend-module-github-provider            0.3.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.3.1
  @backstage/plugin-auth-backend-module-google-provider            0.3.1
  @backstage/plugin-auth-backend-module-guest-provider             0.2.6
  @backstage/plugin-auth-backend-module-microsoft-provider         0.3.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.4.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.6
  @backstage/plugin-auth-backend-module-oidc-provider              0.4.1
  @backstage/plugin-auth-backend-module-okta-provider              0.2.1
  @backstage/plugin-auth-backend-module-onelogin-provider          0.3.1
  @backstage/plugin-auth-backend                                   0.24.4
  @backstage/plugin-auth-node                                      0.5.6, 0.6.1
  @backstage/plugin-auth-react                                     0.1.13
  @backstage/plugin-bitbucket-cloud-common                         0.2.28
  @backstage/plugin-catalog-backend-module-github-org              0.3.8
  @backstage/plugin-catalog-backend-module-github                  0.7.11
  @backstage/plugin-catalog-backend-module-logs                    0.1.6
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.4
  @backstage/plugin-catalog-backend-module-unprocessed             0.5.4
  @backstage/plugin-catalog-backend                                1.30.0
  @backstage/plugin-catalog-common                                 1.1.3
  @backstage/plugin-catalog-graph                                  0.4.17
  @backstage/plugin-catalog-import                                 0.12.11
  @backstage/plugin-catalog-node                                   1.16.1
  @backstage/plugin-catalog-react                                  1.16.0
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.7
  @backstage/plugin-catalog-unprocessed-entities                   0.2.15
  @backstage/plugin-catalog                                        1.28.0
  @backstage/plugin-devtools-backend                               0.5.3
  @backstage/plugin-devtools-common                                0.1.15
  @backstage/plugin-devtools                                       0.1.25
  @backstage/plugin-events-backend                                 0.5.0
  @backstage/plugin-events-node                                    0.4.9
  @backstage/plugin-home-react                                     0.1.24
  @backstage/plugin-home                                           0.8.6
  @backstage/plugin-kubernetes-backend                             0.19.4
  @backstage/plugin-kubernetes-common                              0.9.4
  @backstage/plugin-kubernetes-node                                0.2.4
  @backstage/plugin-kubernetes-react                               0.5.5
  @backstage/plugin-kubernetes                                     0.12.5
  @backstage/plugin-notifications-backend                          0.5.4
  @backstage/plugin-notifications-common                           0.0.8
  @backstage/plugin-notifications-node                             0.2.13
  @backstage/plugin-notifications                                  0.5.3
  @backstage/plugin-org                                            0.6.37
  @backstage/plugin-permission-backend                             0.5.55
  @backstage/plugin-permission-common                              0.8.4
  @backstage/plugin-permission-node                                0.8.8, 0.9.0
  @backstage/plugin-permission-react                               0.4.32
  @backstage/plugin-proxy-backend                                  0.6.0
  @backstage/plugin-proxy-node                                     0.1.2
  @backstage/plugin-scaffolder-backend-module-azure                0.2.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.7
  @backstage/plugin-scaffolder-backend-module-github               0.5.5
  @backstage/plugin-scaffolder-backend-module-gitlab               0.7.1
  @backstage/plugin-scaffolder-backend-module-notifications        0.1.8
  @backstage/plugin-scaffolder-backend                             1.29.0
  @backstage/plugin-scaffolder-common                              1.5.10
  @backstage/plugin-scaffolder-node                                0.6.3, 0.8.0
  @backstage/plugin-scaffolder-react                               1.14.6
  @backstage/plugin-scaffolder                                     1.27.5
  @backstage/plugin-search-backend-module-catalog                  0.3.2
  @backstage/plugin-search-backend-module-elasticsearch            1.7.0
  @backstage/plugin-search-backend-module-pg                       0.5.42
  @backstage/plugin-search-backend-module-techdocs                 0.4.0
  @backstage/plugin-search-backend-node                            1.3.9
  @backstage/plugin-search-backend                                 2.0.0
  @backstage/plugin-search-common                                  1.2.17
  @backstage/plugin-search-react                                   1.8.7
  @backstage/plugin-search                                         1.4.24
  @backstage/plugin-signals-node                                   0.1.18
  @backstage/plugin-signals-react                                  0.0.11
  @backstage/plugin-techdocs-addons-test-utils                     1.0.46
  @backstage/plugin-techdocs-backend                               2.0.0
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.22
  @backstage/plugin-techdocs-node                                  1.13.1
  @backstage/plugin-techdocs-react                                 1.2.15
  @backstage/plugin-techdocs                                       1.12.4
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.20
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.6
  @backstage/theme                                                 0.2.19, 0.5.7, 0.6.4
  @backstage/types                                                 1.2.1
  @backstage/version-bridge                                        1.0.11

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@darrenyung so I'm actually not sure 100% of the cause here, but it looks like it's something to do with incompatible versions of the `opentelemetry` ecosystem being brought in and they just don't like up correctly.

`opentelemetry` has just released version 2, so my guess here is that one of the many supporting otel packages maybe has had an incorrect semver bump and ends up breaking in some weird ways. I don't really know the ins and outs of the packages, but we managed to reproduce this internally too, and the `meter` gets created, but it definitely doesn't have `createGauge` on the prototype, but it does have `createObservableGauge`.

```ts
 Meter {
  _meterSharedState: MeterSharedState {
    _meterProviderSharedState: MeterProviderSharedState {
      resource: [Resource],
      viewRegistry: [ViewRegistry],
      metricCollectors: [Array],
      meterSharedStates: [Map]
    },
    _instrumentationScope: { name: 'default', version: '', schemaUrl: undefined },
    metricStorageRegistry: MetricStorageRegistry {
      _sharedRegistry: Map(0) {},
      _perCollectorRegistry: [Map]
    },
    observableRegistry: ObservableRegistry { _callbacks: [], _batchCallbacks: [] },
    meter: [Circular *1]
  }
}
```

That said, there is a fix although I'm not sure that we can do anything in the Backstage repo for it, as it looks like it's something adopters have to do.

We ended up bumping the below packages to the latest versions:

```json
    "@opentelemetry/api": "^1.9.0",
    "@opentelemetry/auto-instrumentations-node": "^0.57.0",
    "@opentelemetry/exporter-prometheus": "^0.200.0",
    "@opentelemetry/sdk-node": "^0.200.0",
    "@opentelemetry/sdk-metrics": "^2.0.0",
```

And it looks like the `@opentelemetry/sdk-node` and `@opentelemetry/exporter-prometheus` to `0.200.0` are the ones that fix this. https://github.com/open-telemetry/opentelemetry-js/releases/tag/v2.0.0 mentions that only `0.200.0` packages are only compatible with the 2.x release which is why I'm leaning down the path that something has been updated an only compatible with the 2.x release as a patch or something :shrug:

Can you try and bump those two packages and see if it works for you? Not sure what this means for 2.x adoption in Backstage, maybe we should create a ticket to migrate to the latest version too :pray:

**Comment by darrenyung** [comment]
Thanks @benjdlambert . Will give this a go and report back

**Comment by darrenyung** [comment]
hi @benjdlambert , tried adding this to the backend's package.json file. Error still persists, even if I add both the suggested libraries to the resolutions. Since its the OTEL, I've also managed to replicate this locally now as the feature is turned off by default for development.

Here's my libraries related to OTEL

```
   "@opentelemetry/api": "^1.9.0",
    "@opentelemetry/auto-instrumentations-node": "^0.57.0",
    "@opentelemetry/core": "^1.30.1",
    "@opentelemetry/exporter-prometheus": "^0.200.0",
    "@opentelemetry/instrumentation-http": "^0.53.0",
    "@opentelemetry/sdk-metrics": "^2.0.0",
    "@opentelemetry/sdk-node": "^0.200.0",
```

**Comment by benjdlambert** [comment]
@darrenyung can you put together a reproduction repository or something to help us dig in a little bit.

You can probably use your original yarn.lock and run `yarn install` in the new example repo to keep the same versions that you already have locked.

It's going to help us understand what's going on here and different ways to reproduce this :pray:

**Comment by darrenyung** [comment]
@benjdlambert - Thanks! I'll try. I'll need to figure out a way to modify the file for public use due to corporate restrictions.

**Comment by darrenyung** [comment]
Hi @benjdlambert , after couple of investigations, have found out that our wrapper library for otelapi lib is running on a lower version whilst Backstage is on 1.9. This caused the failure and I've switched the implementation across to NodeSDK public library as temporary measure. Its now starting up as normal for me in my local env. Will push for the deployment in our higher envs and test the stability of it.

**Comment by darrenyung** [comment]
Closing issue as its self-inflicted by in-house library package.
