### ISSUE TITLE
🐛 Bug Report: `providers.okta.resolvers.emailMatchingUserEntityProfileEmail()` is not a function in plugin-auth-backend 0.20.1

### ISSUE THREAD

**Issue by LegendSebastianoL** [backstage/backstage#21949]
### 📜 Description

As per title my working backend auth which uses `providers.okta.resolvers.emailMatchingUserEntityProfileEmail()` now throw an error with `is not a function` in plugin-auth-backend 0.20.1.

Apparently the only resolver available now is `emailMatchingUserEntityAnnotation` which doesn't work for me without changing something else, I haven't fully debugged it as I'm in the middle of an upgrade so for now I stick with V. 0.20.0

### 👍 Expected behavior

after updating plugin-auth-backend to 0.20.1 I should be able to log into backstage

### 👎 Actual Behavior with Screenshots

`providers.okta.resolvers.emailMatchingUserEntityProfileEmail() is not a function` which prevent users to log into backstage 
![Screenshot 2023-12-20 at 08 31 50](https://github.com/backstage/backstage/assets/61748264/0dd3eb28-bf64-40ee-85f1-0768f3af0772)

### 👟 Reproduction steps

update backstage to the latest version 1.21.0 which includes "@backstage/plugin-auth-backend": "0.20.1" and use okta as a auth provider

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
yeah this looks like an issue. Thanks for reporting this @LegendSebastianoL 🙏
We are on it
