### ISSUE TITLE
🐛 Bug Report: catalog-backend-module-github installation impossible on >=1.25.0

### ISSUE THREAD

**Issue by sheershoff** [backstage/backstage#24354]
### 📜 Description

1. Installed backstage 1.25.0, ran the `yarn backstage-cli versions:bump`, so it's upgraded to `1.26.0`
2. Ran `yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-github`
3. Trying to include this plugin according to https://backstage.io/docs/integrations/github/discovery and https://backstage.io/docs/integrations/github/org
4. Created a GitHub app, included it's secrets according to the instruction
5. Stuck on the including the plugin itself:
  1. Instructions say to update `packages/backend/src/plugins/catalog.ts` file, but it's not there since `1.25.0`
  2. Tried just adding `backend.add(import('@backstage/plugin-catalog-backend-module-github'));` to `packages/backend/src/index.ts`, but the `yarn dev` spits out some compilation errors and the backstage instance just doesn't work.

### 👍 Expected behavior

The `plugin-catalog-backend-module-github` should be working with installations on `1.25.0` or `1.26.0` and further and the instructions should be updated.

Guess it's not updated for the new backend system yet.

### 👎 Actual Behavior with Screenshots

```
❯ yarn dev                                                                       
yarn run v1.22.22
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://[::1]:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/sheershoff/project/backstage-local-test/backstage-local-test-v1-25-2/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all
[1] /Users/sheershoff/project/backstage-local-test/backstage-local-test-v1-25-2/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:104
[1]       throw new Error(
[1]             ^
[1] 
[1] 
[1] Error: Failed to add feature, invalid type 'undefined'
[1]     at BackendInitializer.addFeature_fn (/Users/sheershoff/project/backstage-local-test/backstage-local-test-v1-25-2/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:104:13)
[1]     at BackendInitializer.doStart_fn (/Users/sheershoff/project/backstage-local-test/backstage-local-test-v1-25-2/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:156:7)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at BackendInitializer.start (/Users/sheershoff/project/backstage-local-test/backstage-local-test-v1-25-2/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:149:5)
[1]     at BackstageBackend.start (/Users/sheershoff/project/backstage-local-test/backstage-local-test-v1-25-2/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:42:11)
[1] 
[1] Node.js v20.12.2
[0] webpack compiled successfully
```

then the instance shows page with `Enter as a Guest User` with `failed to fetch` popup, when I click `ENTER` I see

```
Error 1 of 1
TypeError
Failed to fetch
Call Stack
 ProxiedSignInIdentity.fetchSession
  node_modules/@backstage/core-components/dist/index.esm.js:6721:28
```

### 👟 Reproduction steps

1. `npx @backstage/create-app@latest`
2. `cd backstage-v-1-26-0`
3. `yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-github`
4. try including the plugin according to instructions at https://backstage.io/docs/integrations/github/discovery and https://backstage.io/docs/integrations/github/org

### 📃 Provide the context for the Bug.

Trying to start using backstage

### 🖥️ Your Environment

```
❯ yarn backstage-cli info
yarn run v1.22.22
$ /Users/sheershoff/project/backstage-local-test/backstage-local-test-v1-25-2/node_modules/.bin/backstage-cli info
OS:   Darwin 23.4.0 - darwin/arm64
node: v20.12.2
yarn: 1.22.22
cli:  0.26.3 (installed)
backstage:  1.26.0

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.7.0
  @backstage/backend-common                                        0.21.7
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/catalog-client                                        1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.3
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.14.4
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-guest-provider             0.1.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.0
  @backstage/plugin-catalog-backend-module-github                  0.6.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-github-actions                                 0.6.15
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.14
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.4
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.22
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-tech-radar                                     0.7.3
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 1.02s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by 0GiS0** [comment]
I feel your pain! Same situation here ☹️

**Comment by 0GiS0** [comment]
Hi again,

hey @sheershoff I found the way it works now:

Install the module as the documentation says:

`yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-github
`

and then import the plugin in the `packages/backend/src/index.ts` using this:

```
// github discovery
backend.add(import('@backstage/plugin-catalog-backend-module-github/alpha'));
```

>Note: the `/alpha` is the key 😃

I've tested it with this configuration in my app-config.yaml

```
catalog:
  providers:
    github:
      returngisOrg:
        organization: returngis
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: main
        schedule:
          frequency: { minutes: 5 }     
          timeout: { minutes: 3 }   
```

And it works 🎉

I've created a [PR](https://github.com/backstage/backstage/pull/24416) with this info.

Hope it helps!

**Comment by Rugvip** [comment]
@0GiS0 thank you! 👍 

Closing, since the documentation is now updated
