### ISSUE TITLE
🐛 Bug Report: techdocs-cli publish stopped working in version 1.8.12

### ISSUE THREAD

**Issue by EddieWhi** [backstage/backstage#25323]
### 📜 Description

We've been calling the following in CI which has started failing since 1.8.12 release

```
npm install -g @techdocs/cli
techdocs-cli publish --publisher-type awsS3 --storage-name something --entity something --directory some_dir
```

Have worked around this by pinning the version back to 1.8.11.

### 👍 Expected behavior

Techdocs publishes as in 1.8.11

### 👎 Actual Behavior with Screenshots

Error message:
```
Cannot find module 'morgan'
Require stack:
- /techdocs/node_modules/@backstage/backend-common/dist/index.cjs.js
- /techdocs/node_modules/@techdocs/cli/dist/cjs/publish-CnXRqKHz.cjs.js
- /techdocs/node_modules/@techdocs/cli/dist/index.cjs.js
- /techdocs/node_modules/@techdocs/cli/bin/techdocs-cli
```

### 👟 Reproduction steps

```
npm install @techdocs/cli@1.8.12
npx techdocs-cli publish --publisher-type awsS3 --storage-name something --entity something --directory some_dir
```

### 📃 Provide the context for the Bug.

Publishing techdocs to s3 no longer works. We have a workaround for now (downgrading) so impact limited.

### 🖥️ Your Environment

CI is running node v16.15.1 (don't ask) in a container.
Have tested locally with node v20.9.0 on macos and got the same result.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by EddieWhi** [comment]
Just seen that this is a duplicate of #25303 (sorry) which has been closed... will close this one
