### ISSUE TITLE
Scaffolder Action Fetch Cookicutter: tsc error with action definition since 1.40.0

### ISSUE THREAD

**Issue by JoergSiebahn** [backstage/backstage#30302]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
tsc cookiecutter
```

### 🗃️ Project Area

Software Templates

### 🔗 External Integration

N/A

### 📝 Description & Context

Since Backstage 1.40.0 `yarn tsc:full` raises an error with the TemplateAction created by plugin-scaffolder-backend-module-cookiecutter:

```
node_modules/@backstage/plugin-scaffolder-backend-module-cookiecutter/dist/index.d.ts:53:54 - error TS2344: Type '{ url: string; values: Record<string, unknown>; targetPath?: string | undefined; copyWithoutRender?: string[] | undefined; extensions?: string[] | undefined; imageName?: string | undefined; }' does not satisfy the constraint 'JsonObject'.
  Property 'values' is incompatible with index signature.
    Type 'Record<string, unknown>' is not assignable to type 'JsonValue | undefined'.
      Type 'Record<string, unknown>' is missing the following properties from type 'JsonValue[]': length, pop, push, concat, and 29 more.

 53 }): _backstage_plugin_scaffolder_node.TemplateAction<{
                                                         ~
 54     url: string;
    ~~~~~~~~~~~~~~~~
... 
 59     imageName?: string | undefined;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 60 }, {
    ~


Found 1 error in node_modules/@backstage/plugin-scaffolder-backend-module-cookiecutter/dist/index.d.ts:53
```

As far as I could track the changes, I assume it has been introduced in #30116. The API changes result in [`values: Record<string, unknown>`](https://github.com/backstage/backstage/pull/30116/files#diff-6cebc85fe9f7147b083107dd9ef50ef554dc58c0b73b1f222265716899318a87R50). As I understand the generics here, all properties of a `TemplateAction.schema.input` must be of type `JsonValue` and a value type `unknown` of a `Record` does not meet this requirement.

I see that [the type verification passed](https://github.com/backstage/backstage/actions/runs/15414006778/job/43372626946) for #30116, but it doesn't in a new Backstage app (see reproduction). I'm a bit confused by this difference.

### 👍 Expected Behavior

When executing `yarn tsc:full`, I don't get errors from Backstage dependencies in `node_modules`.

### 🥾 Reproduction steps

1. Create a new backstage app

```console
/tmp$ nvm use 20
Now using node v20.12.2 (npm v10.5.0)
/tmp$ npx @backstage/create-app@latest
...
? Enter a name for the app [required] my-backstage
...
/tmp$ cd my-backstage
```

2. Add plugin-scaffolder-backend-module-cookiecutter

```console
/tmp/my-backstage$ yarn workspace backend add "@backstage/plugin-scaffolder-backend-module-cookiecutter@^0.3.11"
...
```

3. Import the module in the app

This will add the module import after `backend.start()`, but the location does not make a difference for `yarn tsc:full`.

```console
/tmp/my-backstage$ echo "backend.add(import('@backstage/plugin-scaffolder-backend-module-cookiecutter'));" >> packages/backend/src/index.ts
```

4. Install and verify

```console
/tmp/my-backstage$ yarn install
/tmp/my-backstage$ yarn tsc:full
node_modules/@backstage/plugin-scaffolder-backend-module-cookiecutter/dist/index.d.ts:53:54 - error TS2344: Type '{ url: string; values: Record<string, unknown>; targetPath?: string | undefined; copyWithoutRender?: string[] | undefined; extensions?: string[] | undefined; imageName?: string | undefined; }' does not satisfy the constraint 'JsonObject'.
  Property 'values' is incompatible with index signature.
    Type 'Record<string, unknown>' is not assignable to type 'JsonValue | undefined'.
      Type 'Record<string, unknown>' is missing the following properties from type 'JsonValue[]': length, pop, push, concat, and 29 more.

 53 }): _backstage_plugin_scaffolder_node.TemplateAction<{
                                                         ~
 54     url: string;
    ~~~~~~~~~~~~~~~~
... 
 59     imageName?: string | undefined;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 60 }, {
    ~


Found 1 error in node_modules/@backstage/plugin-scaffolder-backend-module-cookiecutter/dist/index.d.ts:53

```

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Undecided

**Comment by benjdlambert** [comment]
What version of `@backstage/plugin-scaffolder-module-cookiecutter` do you have locally?

Did you use `yarn backstage-cli versions:bump` to bump to the latest version? It should pull in `0.3.11`.

It looks like you have outdated code as this PR converted those actions to use the latest `createTemplateAction` https://github.com/backstage/backstage/pull/30116/

**Comment by JoergSiebahn** [comment]
Hi @benjdlambert,

thank you for looking into this. 

> What version of @backstage/plugin-scaffolder-module-cookiecutter do you have locally?

As of `node_modules/@backstage/plugin-scaffolder-backend-module-cookiecutter/package.json` in the project it is `0.3.11`.

> Did you use yarn backstage-cli versions:bump to bump to the latest version?

Yes, followed by a `yarn dedupe`. `yarn.lock` shows `0.3.11` and backstage-cli bumped to `^0.3.11` in `package.json`.

> It looks like you have outdated code as this PR converted those actions to use the latest createTemplateAction https://github.com/backstage/backstage/pull/30116

I'm pretty sure I use plugin-scaffolder-module-cookiecutter 0.3.11 as described above.
Am I missing something else that needs to be updated?

Please also have a look at the reproduction steps above. I was able to reproduce the issue with a brand new Backstage app only with the defaults from `npx @backstage/create-app@latest` and the `plugin-scaffolder-module-cookiecutter`.

**Comment by JoergSiebahn** [comment]
Just for reference: `plugin-scaffolder-node` is at `0.9.0`. I think that is the plugin that defines in general `createTemplateAction` which changed in #30142.

The declaration of `createTemplateAction` [references](https://github.com/backstage/backstage/blob/ddb0939b4a23ca0c4254a95abef12c1fe2029b44/plugins/scaffolder-node/src/actions/createTemplateAction.ts#L82) a variant of `TemplateActionOptions` which uses `JsonObject` from the error message for `TActionInput` and `TActionOutput`.

Tbh, the types and inheritance in that file overload my head a bit.

What I can spot is this:

The [`action` parameter in `createTemplateAction`](https://github.com/backstage/backstage/blob/ddb0939b4a23ca0c4254a95abef12c1fe2029b44/plugins/scaffolder-node/src/actions/createTemplateAction.ts#L83-L98) uses two times `TInputSchema` and two times `TOutputSchema` while [the definition in `TemplateActionOptions`](https://github.com/backstage/backstage/blob/ddb0939b4a23ca0c4254a95abef12c1fe2029b44/plugins/scaffolder-node/src/actions/createTemplateAction.ts#L30-L44) declares `TActionInput`, `TActionOutput`, `TInputSchema` and `TOutputSchema`. `TActionInput` and `TActionOutput` extend `JsonObject` which is mentioned in the tsc error and the definition of `createTemplateAction` has neither of them.

Could this introduce a problem?

EDIT: Could it be just luck that all the Zod functions in the end resolve to a type that is valid for the `JsonSchema` type, just `z.unknown()` doesn't? I couldn't find `z.unknown` in any other use of `createTemplateAction`.

**Comment by benjdlambert** [comment]
Hmm very interesting... I think that the error is valid, and we should have caught this in the main repo. I remember doing that type and going 'oh I wonder if this works', and it didn't complain.

Will investigate as to why this is broken in our main repo, but I think there's a pretty simple fix for this which is just to change the cookiecutter type to `z.record(z.string(), z.any())` should be fine. 

Another option, would be just to set it as `z.object({}).passthrough()`

**Comment by benjdlambert** [comment]
@JoergSiebahn I shipped a fix for this yesterday so closing.

Should be available in https://github.com/backstage/backstage/releases/tag/v1.40.1

**Comment by JoergSiebahn** [comment]
Thank you so much for the fast fix, @benjdlambert. Works great. 🚀
